### ISSUE TITLE
[RFC] Proposal for permissioned transfers.

### ISSUE THREAD

**Issue by Tamgros** [solana-labs/solana-program-library#3381]
**User stories of potential use cases**

- Token Creator only want tokens to be tradable between trusted entities
    - Example: custodial wallet to custodial wallet of different video games in the same platform
- Token Creator want trusted entities to be able to send tokens anywhere, including non trusted entities, but non trusted entities can only send tokens to trusted entities
    - Users can own tokens in their self custodies wallets, but can only trade back to a trusted party
- deny/blocklist - can send to all addresses except for a few addresses
    - Note, this one seems hard because blocked entities can just create a new address

Note: In each case, the Token Creator may want to be able to grant **and** revoke permissions for the trusted entities. 

In the current state, users have to:
- use a freeze/transfer/thaw tx sequence on the client side, which requires a signature from the freeze authority, pretty heavy handed centralization
- See below “From Jerry” explaining a wrapped token, but still requires a multisig PDA.

### **Proposal**:

**From brief convo Jon Cinque**, Some "privileged" extension that holds approved accounts with the two modes of operation:

- accounts may only be owned by someone on a list
- accounts can be owned by anyone, but transfers only permitted to someone on the list (if you're not on the list)

We'll probably need to consider additional maintenance tasks for the list

**From Jon Wong**

- use a non-transferrable NFT (or SFT) to represent trustedness , and gate access through token ownership
    - Main drawback is potentially cost of minting entire tokens for this purpose
    - Unclear how revoking permissions would work in this case

**Issues:**

- ~2k approved authorities would essentially be the max you can easily store and be accessed with an on chain check

**Appendix**

From Jerry: 
For the signing case

The token could initially look like this:

```
Token:
   mint: ...
   owner: Matt
   freeze_auth: Mulitsig(PDA(phase 1), PDA(phase 2))
   amount: 1000
   frozen: true
```

When you interact with either contract (say to transfer out 100$), the PDA signs to thaw the account, owner also signs to authorize transfer. State changes to:

```
Token:
   mint: ...
   owner: Matt
   freeze_auth: Mulitsig(PDA(phase 1), PDA(phase 2))
   amount: 1000
   frozen: false
```

This is like an unlock. Then a transfer occurs + an array of other checks/logic. Finally, the PDA signs again to refreeze the account. Final state:

```
Token:
   mint: ...
   owner: Matt
   freeze_auth: Mulitsig(PDA(phase 1), PDA(phase 2))
   amount: 900
```
